name: Clarive Zmvscmd Plugin
description: The ZMVSCMD plugin will allow you to execute z/OS commands into your Mainframe from Clarive.
version: 1.0
icon: https://cdn.rawgit.com/clarive/cla-zmvscmd-plugin/master/public/icon/zmvscmd-service.svg?sanitize=true
url: https://github.com/clarive/cla-zmvscmd-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-zmvscmd-plugin
